// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdXzh0bdtSBdkDauazU5ucQg8rBXP8PqY',
    appId: '1:642930496088:web:98633dcfe9e153d95cf02d',
    messagingSenderId: '642930496088',
    projectId: 'tes-firebase-bf0c4',
    authDomain: 'tes-firebase-bf0c4.firebaseapp.com',
    databaseURL: 'https://tes-firebase-bf0c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-firebase-bf0c4.appspot.com',
    measurementId: 'G-3WJFCRVM21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7sqKDkVH9gXApjBzfH_begL6pOqkho-M',
    appId: '1:642930496088:android:55149838a4c4f12b5cf02d',
    messagingSenderId: '642930496088',
    projectId: 'tes-firebase-bf0c4',
    databaseURL: 'https://tes-firebase-bf0c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-firebase-bf0c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQ8odl9kxgv04wtjx2MSYhcwo1DoU4LI',
    appId: '1:642930496088:ios:388855a4f1ba996a5cf02d',
    messagingSenderId: '642930496088',
    projectId: 'tes-firebase-bf0c4',
    databaseURL: 'https://tes-firebase-bf0c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-firebase-bf0c4.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQ8odl9kxgv04wtjx2MSYhcwo1DoU4LI',
    appId: '1:642930496088:ios:5e8b9988b541579c5cf02d',
    messagingSenderId: '642930496088',
    projectId: 'tes-firebase-bf0c4',
    databaseURL: 'https://tes-firebase-bf0c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-firebase-bf0c4.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
